### ISSUE TITLE
Keep state of playing podcast

### ISSUE THREAD

**Issue by venikman** [superchargejs/superchargejs.com#19]
While listening to the first podcast I decided to start a new one and don't wait for the end of the first. I was expecting that the previous podcast will stop to play but it didn't. Looks like here you use transistor.fm and you them as `iframe`, I don't have to experience with `iframes` so not sure if you can keep the state in handlebars. But I think ( with any implementation) you can't have 2 audios to be playing.

**Comment by marcuspoehls** [comment]
@venikman Hey, good point. Up to this point, each episode runs in its own player. It didn't keep track of other episodes. I replaced the list of episodes with a multi-episode player: https://superchargejs.com/podcast

This simpler to maintain and also keeps the state accordingly. Thank you for pointing me to this!
